linters-settings:
  errcheck:
    exclude: .errcheck-excludes
  golint:
    min-confidence: 0
  lll:
    line-length: 100
    tab-width: 4
  goimports:
    local-prefixes: github.com/demosdemon/update-gitignore

linters:
  enable-all: true
  disable:
    - gochecknoglobals
