language: go
env:
  global:
    - GO111MODULE=on
    - secure: MKONE9/YgmlNO0mggFILpY7Uw65WET8n2n1jmgYaJ6+ppFGU84hjGZf+DT7o1j7cI6h0w0ZyldLGFjCPUfglW9itY2n377zXEz6o5kJJSWHzOtN75tueimVVv+bU69SJjp920KvcRrb4qKNcC1YiFTtd+UfzlsgEnQeRXfGOFhqlV7zFBLLe0xHqPMWbBzsjBZC7zuVFxpp41E2jPTZmdfDVzjORz2m2a5CCOfWhIRUrIOsyhDLCD+rj/mMdwja5HtfWrcf3+DrN1vgvwxVcGYUyDPRx4RX/EYcuEU3fwghsfeXAi37StGR/N1fj9H2zDB87/XbtnW1x4XCwnMNWcK1r4CkI8DzpyfO5rijYG2tJdv00VzKCMb/Y/KtDzC9wcxNhYfRw6ABCpoUjR0PKsWx+BBjsy2iXrA0sYX68SOy6PmovNS5mp/SJKeyJPIy6QkhoZU7KjjtlR/upMichkse3Po5w/A74Qc6VjRCiDYGayMnH7cF6K365G6tFWJQ7D/NON8pD1y4faovG2Rqnag/fC7JZ9pLqIFyk8Kt8ZWLdXJ4bfWKYqt7EfLqVYsd2ByPDdwqj3THhHO4NnKuu63Q6EKTkbxC0j+q48QD5DmhQHDz0vo9mGmVIvAfIZ1ACfhtPeg/bB0sHRFCPwxu+ZBK/3DSLef/AsPZalIQoGU8=
    - secure: g5qQoGabuQvxnWiXtyz8+d1q2tUHH2dQFuyWlpwL42b839T7tC3HSYnnzKzXirkW1hZIBAJg+IPuLJvM2kp+oakOjQydQAaX7/JSa+zSgeePjiUizWUEejRtAZTD9hIlusaOtXbZvi3CoAk+cDPSnPImcsyq1thA0mxY2G0adNT/APteBpUmRtxgBoYQS4lpxCOtH1Ne53E2m7lxmeruyfjM+ZLpUYq30JjlhNi+NGbifMgOz4FiCjm7c7a0h2DFNyukmJeHE+GxlwEl/RuTXLlf9ZawSNtFNrK+yh8hyGPrG1V7mjJLEwuo3TTz3/bEY/Ukhv5y17Q6MWfjCLxxl8duYyEU97JX+D32XwXoncC2Wm/G1JhrL4utm6OYB+GTccbBUHkX9+v/yD9IMEIh4ppPFtDspjS0MYIGfyD542RF9qU4ImcBTFL5eCnbYAAl8W7iJ4lhxWlluG8f6iFeGXtHxHIM7skXHMgJWIv5x+HtQplNR11BQJEJwjF1cF9F+WipOOUlkUp+2/oivJeIDIapfkNEJRCnWZ0kY6+ONZqkgeJGQbnobK7eSIj19DAkK/pGp8zqaWnWLBKwgxjdec8/ICCSYoCrz/MiHaS6S9V2MGgI4dPr1Eae/3t7SS4wHFhqO5tGvIQ93+K97auVSwGX4UwiKlgPunVFJ5BaRoA=
    - secure: Tc/Ae4H+8/scx7v5PJ7pNNYjvu6fUKoAYsX52XAFoKe1RUEjSa2n813bhWWxUksDDJ+mkJKFuS6L3cNkBtYAEe2/fdN1nLKqEY8k5WpCMZ2hNA9ZUKRlO5omzbdTtpV9dCJzZPgdYvopC5KcSXqY5GveYtoFA9/zrVbYCuvlh6iwDbpJ8/ri5YqgC2aPdz4FKkHh0WHP1xd8d9XxcZXwlHtispM2V4TtuEpl32c3kXJgOSQViwJloKDWNjKFqOqZ1jPJ3+4UiiPmy1lbmaI6MN8d/nS0FKALQV/WxnrDeo+67MoZeGhuS3kkzTFMUDm+njQfWp2/dIBKlZBO7xcZ90P5UK/+ABAWjBFZmMN4+7iYpc+3CQr/5XBZZ/h8W4aa0eerlPUtxlcSrD1HLm0mcklUum5XFpNmR6TJa4lNt2i59AKHw9/fJccF//QZd7zRcbYFOPBgsZzRmLbG9jrBC44e+fTDRi4qCP2TrUcpe3gqlTz69NYiknSJ+xXeibKy7Xz4lWJIZLUreGCjXifgU2XgxpV05d0c6YPW3drkq/B+0kojn3u5cyJx7IgmTdq7M2VlfV6QMsp6B2Tr2ErQaH2/DUE1tl9Qb9xAQpY8Fbh2YEfg7UVlQ62XTy+GhE1gU3PvsqXNDfjVhCy3iFL+I9jeq05XKBkg6LFlht8Jf3Y=
    - secure: iDOofLLRjvyrI5wGXHmRNNsqiT1fEaB7OqaLyAx1L2X60NgiPo4eYVQi7CkSRIl4Bn7j7UMZ6KlZ1Er1a6ZXPRZ38EqstW2GI+jrp7f1D8dqTLgq4vbxKrqKy/cqd85KOTPFELNSNJ9SBhId11Yuplq5DBZ/NrOFlzbUsUWndRrT3Dit2EdUl/flbfJ+OpDWo5g6v05cwJehenqng+BOfnabE5+sZD7UIHaHxEIZCc5Q14i4kx1gR/1C6apsukSXUycR2sxzvBCM250CeZl0A9HQLwgcviKRNLDhx5Jz+i68pdYC8zbH0gLjBzkUnv6JdRxYjRs79sedf3TTv0snfJRhhVipR4Eftc5iESl2+3rOLChKgIVP2QqQGVAk0RRBvSPZWv25eYid1kqeC0mLrQhtiueM29idrz3ug2Z8QWImkB88DYWB970i/DctitjHFxPWqzh8MEMnKr2k8Z0jY8CLnSVq3IuniXioy50bEzEmD2lCRzfvN2xOikCdYBq4zKxSMlDHsQXWO8ghrfJOpCWD0Acc8CSWbcx1nYCX+85YcqCgoAvrz1Mfb13U534C3GF1PsEqxtC6Udmz8fJZ9o7qZbEDkw8Mui9OHqCGJO/RecJIbBw34qKRAiA9HTVco+8F5vensB9wBjKYQ+0uSz/Fen1a4SeIjH5HglJnCHQ=
    - secure: QIqr9O3Wrk19tNmXbCqaTHQENtcS3sSogMeJSoLQduelxubA1rgBkRqNH15qLpaU9z7xKB9eOwUBgNwQV4JmsKhfHZmrDv0yr+mZbRVsXOvr2Wy4izkDx+76DV9XZVceNxwkO+qobdEYYypFY7kVacLeR6vzlTj0XYx15jnu99Xo8nQUmvAS3FBxK98L8fFc4Rx4lVz2aDUUBX7VIAPZqmRB5f9WihfEZclgn0m97UDG2iSesXMGCaDrtXnGY7eSrDLKxhOg9BtdPRoW+JjZUOKRtiliKAbxK2HCP8D04kkm97GI2TLWJNgmBqjdZxtvvt0tyT0+269Psy3CPBfgIuuEvsIity+hgs0tJ6MO7DJ95IXs2lRfJqj0DvR/zP8xP1rvbLtK6ezMLxwcWfMJeEjt2143hOOhtqNvTAy2f7GVMtTzVp4nRDsEnfwF5hyBxalxbQDgzcB5aHItXLbCAJckX/gxVJilSakq3qF/ITbHwVZJ791Lj2Iz3SsmtIBQyci/AOqYrpwiz9DKxoSVAOS+Wi2DaE0xFwYd7stCg+iTQDC59mNbeyz/YVsPI8/0gU6OoIWw6x5F/yoB8t9Hn0fpIQpPAI9/3xAi+9NgHqgQ4vCoIy5ZjXKYwZF+v35IPqmQlcd1QaaGH7oE1nUjlXgOZS0iuN1j6HN5hsT35wA=

go:
  - 1.12.x
  - master

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - go: master

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b "$(go env GOPATH)/bin" v1.15.0
  - golangci-lint --version
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls

install:
  - go mod vendor

script:
  - golangci-lint run
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - make build
  - ls -l update-gitignore
  - mkdir -p build
  - mv update-gitignore "build/update-gitignore-$(go env GOOS)-$(go env GOARCH)"

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  slack:
    secure: iefNHBLu+kF+JAdxQAt6chIU6VGDMCSSXniARaTp2gq1ERMNeX67WdY4WsqY4R6/EIIPPu0sLR34HnFLgad6IUZiem+zYNmpb4cw+laRE9HC7ItiPr/PRv0oGRa8qx00rogofKPmxYIFKospZ6O3u12s6+b7M8GL59xLk/I92ThiOll/kWnTFEWYcZMYF1IobIjVsvPuoy/P3QPNrtnxUB3+qBMhKSa+0/61AWJbkma8mWnv04VBiHcJGpVYQtH/TCjoQZxsDEm7gx7pF7oW6Fdw+i+sv7+NRdz8lOvLvprUiEePCUlCUh6fIIEne6dRSYT4kKha08t6dba7H5g13egxcaKmqpUlnbyiSIu2I2tPLfEiQgmSLVG1J8bnf0J19kK6QxwZUdFHRN/IypAVjbUVl+CoBOvg9JLOqyCltSiDEEuhT65/VMkulIJDsq6p0E3gkq/f9Xyyy5cPjBJ2viLd1Apgk4KQ9fD64QJryHZl47U+VflRCFaQpvv/B6l6pletFCAMSLqJxycXCjhFlp6FeB2LX8FRdwLau+iwUIeDGxhe0zVWIlIxQV+jBJfl4EKtoEKl6kX6piC02AaRyNg6jwBJWDKjiJvoWB8+gIqWO4ymovzUWExTqCuI13pcbByYbk716OKu2u7kysCx035OR4YcjIwKsdH9SDSWTm4=

addons:
  artifacts:
    s3_region: us-east-2
    paths:
      - build
