language: go
env:
  global:
    - GO111MODULE=on
    - secure: MKONE9/YgmlNO0mggFILpY7Uw65WET8n2n1jmgYaJ6+ppFGU84hjGZf+DT7o1j7cI6h0w0ZyldLGFjCPUfglW9itY2n377zXEz6o5kJJSWHzOtN75tueimVVv+bU69SJjp920KvcRrb4qKNcC1YiFTtd+UfzlsgEnQeRXfGOFhqlV7zFBLLe0xHqPMWbBzsjBZC7zuVFxpp41E2jPTZmdfDVzjORz2m2a5CCOfWhIRUrIOsyhDLCD+rj/mMdwja5HtfWrcf3+DrN1vgvwxVcGYUyDPRx4RX/EYcuEU3fwghsfeXAi37StGR/N1fj9H2zDB87/XbtnW1x4XCwnMNWcK1r4CkI8DzpyfO5rijYG2tJdv00VzKCMb/Y/KtDzC9wcxNhYfRw6ABCpoUjR0PKsWx+BBjsy2iXrA0sYX68SOy6PmovNS5mp/SJKeyJPIy6QkhoZU7KjjtlR/upMichkse3Po5w/A74Qc6VjRCiDYGayMnH7cF6K365G6tFWJQ7D/NON8pD1y4faovG2Rqnag/fC7JZ9pLqIFyk8Kt8ZWLdXJ4bfWKYqt7EfLqVYsd2ByPDdwqj3THhHO4NnKuu63Q6EKTkbxC0j+q48QD5DmhQHDz0vo9mGmVIvAfIZ1ACfhtPeg/bB0sHRFCPwxu+ZBK/3DSLef/AsPZalIQoGU8=
    - secure: g5qQoGabuQvxnWiXtyz8+d1q2tUHH2dQFuyWlpwL42b839T7tC3HSYnnzKzXirkW1hZIBAJg+IPuLJvM2kp+oakOjQydQAaX7/JSa+zSgeePjiUizWUEejRtAZTD9hIlusaOtXbZvi3CoAk+cDPSnPImcsyq1thA0mxY2G0adNT/APteBpUmRtxgBoYQS4lpxCOtH1Ne53E2m7lxmeruyfjM+ZLpUYq30JjlhNi+NGbifMgOz4FiCjm7c7a0h2DFNyukmJeHE+GxlwEl/RuTXLlf9ZawSNtFNrK+yh8hyGPrG1V7mjJLEwuo3TTz3/bEY/Ukhv5y17Q6MWfjCLxxl8duYyEU97JX+D32XwXoncC2Wm/G1JhrL4utm6OYB+GTccbBUHkX9+v/yD9IMEIh4ppPFtDspjS0MYIGfyD542RF9qU4ImcBTFL5eCnbYAAl8W7iJ4lhxWlluG8f6iFeGXtHxHIM7skXHMgJWIv5x+HtQplNR11BQJEJwjF1cF9F+WipOOUlkUp+2/oivJeIDIapfkNEJRCnWZ0kY6+ONZqkgeJGQbnobK7eSIj19DAkK/pGp8zqaWnWLBKwgxjdec8/ICCSYoCrz/MiHaS6S9V2MGgI4dPr1Eae/3t7SS4wHFhqO5tGvIQ93+K97auVSwGX4UwiKlgPunVFJ5BaRoA=
    - secure: wKJZ88HMzUXGfFCA5Z5Z9bSL3mfB04/mFs6QRrq/f8KObs+nkQQqqqGj43LNJXO6ZygVPZAQhUnemsBrrnm3rPJid1gfvYPczQ2QrmqgI2BmVCLFlJJsDqa2DJbMtzjkYk8fZlyGWIvLtHHiLmqB76gm3AGDpTbJAPI9izliz5uPhzV4KGmwpjjsrQ/O/qMLrDJ7lBssvfUQEml0pkpi0nc7dSX5Q+UPKgcd3jURQVZzBjQt4J2rU2wT7BEtXZiNJYO+M1BbSkRs2F4vH9c9ajie+chPRSwrviDhNBdKWxlTK2NKBQWiy+5eXQN5AZh4qhrNmDYsDMl3WQF46NLzp9Op8Zm1L1sjTjWiACXOSeyv+toCrs2pN9nXR3OXXP5YOuDneAzCyHiNuvPsWyVe6llamyA6aGsHnETBsE+4g7sc442bXHsdEH5Eivc4PQZ8DIinOsaz+NWCJqAsVv4L6vvaLbIvYLOPaQRU98A1P3IOaRNc0ChZh5fBODoA4B6pXt0Ujw2ciK9hh1w/CZMaMpMO48jjA2TdN5/sCFhzVtRk3y5/GQIxhQsD45iDvhAgSnEH+/0E1I0ApeOjOgcJw//jPeu+qrgWvawhzGqMLe8T0jCF1cwWvafOpklGe7cbjr2spGLqDDFHscmNZCTQmOjz2jMisvZNuPw4fVXrOdA=
    - secure: Is3kcvu2njSYIffr+FZBJyy7VPt6+uENjKcZV7uXT8ZpsSQCIBk8vwHfomS18/rbpTM7t1Gbbq4f0osyYRHC10PflJEb3WlJ/r/v0nyxnHRpVriEsogEAvCtGeJ8Cmc4GwfWbQT7AJSrYuGWFg+wEZmyWxOdAXHJkL5bX51mwaa6Be42lsW1LCRcyVvwkTqw3xUW/JZ3vtALBP7qaumMnW08watJWIhPZxgcTEoCFWi9Slaab1xwFmwvi99PgFeqd3jHv/7GaPCdKOc69588nv/EODdrrCJCkdnxMZE+R5FiycQ0nO0LMWNoAw+khUzO9PWOL+tqLaglj3/vOn1wDMe2RA6KD/MFwpipiPoNRqYShcZE2HBdMot7Xr3X7jb+eFfj7wzb3X1vJVRHsXn13IhZEukglXo5N+7js4w0lWK/0KOt7k3lk3j/5yNLfRUnd+Am3CaXy4SjjA9R57hcnCXW5sFJuP/qM7sc1oF5J2xmsnMWCFRtxKop9tZA/KaDd5ItxiRLijVpfHweLd5C2S4M7V0pjx3pmKdxRZ1oVRSs9FX7AueajnFwabrHqWxpb0mCVlqQeDrfJWeCOhKWbjgv2SZ8NFhx99CWDpRzmZKCJa4s6jAZNDl4yGxPGiUkK4N+WnfUvqBReFi7RUnFisnXJJpimCISefMJJZCtau0=
    - secure: tpvs8vlig7dUsGbGcajyX/FP7tFwhjm1DLcQWRkrznR4n6T2Nx+OLfqrmcEl/hHqdcH78vkCpsezy4JMeaFHvNBKMBV/YEhXwFMNJ1FzAPrDRXRFWyqxkYMT3lmWBJAfupdz2XTNxDKsLhyU02fxDKJsXmlNDw/pwURX2ds1ER0UouxFnFhb9WLwYA+WxcixgwNHv8zXIbiS29R9ckolr6Ofv6kZ4rKOCF6nY4vA9mnImAHGBcSsl89CqiyhQbGcTcxUmOZN19+kCkxTLXyWyAFMLd9XXXlYLoE2hWpsG+dUW5nlfnUBcvILb03sB/BOhMyJPoovfFf1Jphyb/v9A8LbB4rvPbJ40hHBhMs8gVcA3hNiYTLST7e0m/KzOhvddIrQeqClGLY0Sm9FCLBKBVrijwxza3wTc4QWpflTlERgNi7XQ6sHXya3F4rnWp6PY7HwvwsJdZY1HYlF1P0DIMFbDKaUegWUE4Bn2DTEhppn1W22D266Wa0BMksgJ5NLVLrPrjATMejwNNKOdUlc9FDuGqn1QQThXGRJEAQUyC8C4w3/64omijVSyBu4cotHlihZyfvmyQ1ugUZz6HlVZ1mc0oyBbRMx6rbEBq4ICzc7YIx5R4alAwYNbTyUY076GnqXlfm4utJbuWO6w8oSWyxhs1oAnWMsJmOaY3+WM1w=
    - secure: ZbH1WOIF7NXzGNlNUwpuuKcYxigJRoz1qSel1RbcfcqI/G1S6Ri24kcWNIJdq9uaXUbhC7zuU+Q4sA2jnJZr+v81+esCF8GQhia0mUk2tkoZBInmGiqbgGaJIbwLLJBgasYkO4RelyN5aPbf/tj736LKm8oKJoNY5R5XlLWMayeJdN2fjqCodyHYH9GqQgHwbNfDn/e15pPIUICShkhLBlhzx5FcccM2qo1WRZzNe4XqQIGKaCYZ2j8fTGHOaOC2mpfDfbY8LwzmmCWZWtztecuQsys3AOqyBUxzr66B9lDSNabIYUure4w38v/KxwvwqCE2rIIKChz/tXRBH5QKZsJnrP83fm+uY93/KboWzavcOhpJLE34zqXhVeJ3tzHEs+BZsuHRrNNakRnH1KIlUu830B2Wx451cQ4M+qx2/xPbKuzz762g4dQIlkVqOmv2uMXB+Kb0sKx2VO5ODz2MHT6No1Ii764QkY5x9z2Qkr3YG3oqLGgi8T10oY4ByQz9uchvQxvsswaHpp82GdgGimL4CPEIqVzBsWfN/lDeWRRlhhhVORWBtmyVizltu3SlSahXsgfGslDmuMqOpL4x3aLr219ndgRrwxldZUlbeKiU5LayBD27acaiZR7RpstIN3QcqE6i/J89kP57dmd2L+ATjO7Biw4HzOHmKFyUFhc=

go:
  - 1.12.x
  - master

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - go: master

before_install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.15.0
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/dave/courtney
  - command -v golangci-lint
  - command -v goveralls
  - command -v courtney

install:
  - go mod download

script:
  - golangci-lint run
  - courtney -v
  - make build && ls -l update-gitignore && mkdir -p build && mv update-gitignore "build/update-gitignore-$(go env GOOS)-$(go env GOARCH)"

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  slack:
    secure: iefNHBLu+kF+JAdxQAt6chIU6VGDMCSSXniARaTp2gq1ERMNeX67WdY4WsqY4R6/EIIPPu0sLR34HnFLgad6IUZiem+zYNmpb4cw+laRE9HC7ItiPr/PRv0oGRa8qx00rogofKPmxYIFKospZ6O3u12s6+b7M8GL59xLk/I92ThiOll/kWnTFEWYcZMYF1IobIjVsvPuoy/P3QPNrtnxUB3+qBMhKSa+0/61AWJbkma8mWnv04VBiHcJGpVYQtH/TCjoQZxsDEm7gx7pF7oW6Fdw+i+sv7+NRdz8lOvLvprUiEePCUlCUh6fIIEne6dRSYT4kKha08t6dba7H5g13egxcaKmqpUlnbyiSIu2I2tPLfEiQgmSLVG1J8bnf0J19kK6QxwZUdFHRN/IypAVjbUVl+CoBOvg9JLOqyCltSiDEEuhT65/VMkulIJDsq6p0E3gkq/f9Xyyy5cPjBJ2viLd1Apgk4KQ9fD64QJryHZl47U+VflRCFaQpvv/B6l6pletFCAMSLqJxycXCjhFlp6FeB2LX8FRdwLau+iwUIeDGxhe0zVWIlIxQV+jBJfl4EKtoEKl6kX6piC02AaRyNg6jwBJWDKjiJvoWB8+gIqWO4ymovzUWExTqCuI13pcbByYbk716OKu2u7kysCx035OR4YcjIwKsdH9SDSWTm4=

addons:
  artifacts: true
