language: go
env:
  global:
    - GO111MODULE=on
    - secure: MKONE9/YgmlNO0mggFILpY7Uw65WET8n2n1jmgYaJ6+ppFGU84hjGZf+DT7o1j7cI6h0w0ZyldLGFjCPUfglW9itY2n377zXEz6o5kJJSWHzOtN75tueimVVv+bU69SJjp920KvcRrb4qKNcC1YiFTtd+UfzlsgEnQeRXfGOFhqlV7zFBLLe0xHqPMWbBzsjBZC7zuVFxpp41E2jPTZmdfDVzjORz2m2a5CCOfWhIRUrIOsyhDLCD+rj/mMdwja5HtfWrcf3+DrN1vgvwxVcGYUyDPRx4RX/EYcuEU3fwghsfeXAi37StGR/N1fj9H2zDB87/XbtnW1x4XCwnMNWcK1r4CkI8DzpyfO5rijYG2tJdv00VzKCMb/Y/KtDzC9wcxNhYfRw6ABCpoUjR0PKsWx+BBjsy2iXrA0sYX68SOy6PmovNS5mp/SJKeyJPIy6QkhoZU7KjjtlR/upMichkse3Po5w/A74Qc6VjRCiDYGayMnH7cF6K365G6tFWJQ7D/NON8pD1y4faovG2Rqnag/fC7JZ9pLqIFyk8Kt8ZWLdXJ4bfWKYqt7EfLqVYsd2ByPDdwqj3THhHO4NnKuu63Q6EKTkbxC0j+q48QD5DmhQHDz0vo9mGmVIvAfIZ1ACfhtPeg/bB0sHRFCPwxu+ZBK/3DSLef/AsPZalIQoGU8=
    - secure: g5qQoGabuQvxnWiXtyz8+d1q2tUHH2dQFuyWlpwL42b839T7tC3HSYnnzKzXirkW1hZIBAJg+IPuLJvM2kp+oakOjQydQAaX7/JSa+zSgeePjiUizWUEejRtAZTD9hIlusaOtXbZvi3CoAk+cDPSnPImcsyq1thA0mxY2G0adNT/APteBpUmRtxgBoYQS4lpxCOtH1Ne53E2m7lxmeruyfjM+ZLpUYq30JjlhNi+NGbifMgOz4FiCjm7c7a0h2DFNyukmJeHE+GxlwEl/RuTXLlf9ZawSNtFNrK+yh8hyGPrG1V7mjJLEwuo3TTz3/bEY/Ukhv5y17Q6MWfjCLxxl8duYyEU97JX+D32XwXoncC2Wm/G1JhrL4utm6OYB+GTccbBUHkX9+v/yD9IMEIh4ppPFtDspjS0MYIGfyD542RF9qU4ImcBTFL5eCnbYAAl8W7iJ4lhxWlluG8f6iFeGXtHxHIM7skXHMgJWIv5x+HtQplNR11BQJEJwjF1cF9F+WipOOUlkUp+2/oivJeIDIapfkNEJRCnWZ0kY6+ONZqkgeJGQbnobK7eSIj19DAkK/pGp8zqaWnWLBKwgxjdec8/ICCSYoCrz/MiHaS6S9V2MGgI4dPr1Eae/3t7SS4wHFhqO5tGvIQ93+K97auVSwGX4UwiKlgPunVFJ5BaRoA=
    - secure: JA6CWqqnb1RLpBJ1CKMZl+vvdEfofO2MhJnpWR13Bd0ZJxa9JBn2l6UiTGCV3XqkFa3iVo3lxSArCHiWnWhqVKbPO4q9KcKpb5Yo/TcioUrzDyTvZX2apfiX2Lsz/jsk2w/u/9IGbNvE+27Oyz2RnYf5FCfjNLOtN7GNvS1A4u3l0+l7eMTZFIsM7mINJR8jZmb4nfOqrlHJavuj+GGa6bUmk8DNt3Z4MWYbi9ry2NF3cQfH71ByUAofoKnRM6K0PUxJ59unG4e4DwcLpUFXHtXMllrbhj9uAuxD+y/Sgf6mGsUqfC0FR0jIEFpOwokYG0YdMer6KrIy26Lfm+okU6cfdb322tFl/kMnkJp/f+qlZjaoMGm0k+jdrELWgDXeKc+iff9+QkoS0vk7Qa5NYlj03pEz6I1JpMRvHSNywdvxtpHrpVP2fEaa4xE0pU8EvCQa3IxPzL8zH5jqWLQYcSk9JsKVB46RlQbPAWs4snQH3625EIR48R4UOGsEk8X1UJHyRP3xBUzTYpYGw3SCJVqxMWgwPveBO9XddcMVNBmec6VY3HRkNYQNX3Got+uEeuh2tg7XfPf5JkL4BouY9xAAO7Z0Ko0rFm2wTwS/mbRCooqaOh4PIXUYa8Lutkod63oNtr0GaEr35JbwPnJmPowW8iLod/WiXAwtOoIhc7Y=
    - secure: NhCbI+4PfNXDw7Klpq2B4BQ8SPOwKihdjtR0Xr+HFvNtOfoAtrwCSAogpCI09eswkSAHEuCAcxngAuvhgg4xa8qeOQqtFSJS8VD1e86Y3J5u5aMVuTo/SofjNXHvs3wGu/QfqJHjOCaluG9zlpAPupEVEqqwBRRaElO6dP0m3EL33W8pWmyFwFyffje1rB65tGOveBSatCxFYDojjcOX4D011DCudeFtsqIibEBzhAJwmqh5JVSeq4dqr109g/xzhiZsZVCwZ/SerM0XyWbXU3i/lbgpCo94BGYDJedmu6sLr+lD/QoLdnpYQXA6D4xE8X81ttoNI+PmyizCWmQMhRhMb4ERjQXxaFL7zAyNSb7LwdZhPKtDUzsB5MSjV8y2XMq7ID/pJxgkJ5+uW9UBEU+qOUlI1ud0byoBnueeXMrO0R6OyaCJoCAwBgjaxBc+eD5bRKM+3VOL6HxCw2WBlKUygnu8/g2eaJLIBvePeDLLNVTC9t6ufsAj3ffTTFO1g3cGB+K48piaOTIvDqXlnyParW65PSBSHHx0p1F7HZ6wGvenT7cFOsJn0SsdZOjZtQUc+O5dVlXieN1ZKsAO24vSeNQD+UOLwl27+yx0pUxoL36dZZxBu5tk+YclhLywPl55RfNjrdpQJ4caV64+oQ630vxqTzIdFcFWFPAbrI0=
    - secure: gDdRyhtXYtjxRhyjGMMO+eVq7KqiOhoDDIRaj7Efg6+8j1m7HXHMbL5P5HEaOFXGxg2xx/b2LU2wnvIjfF57PnT652imvhQocuJQrZqKgcPwIxEEhEsHYcMznAXc1FbOgmt4cKyK/vHHdsUySuT0ruTA4Jogjv5OFhkpRzCa5XgFns2S3DnN2dwisv5CrkHcjhjGIakbU9IQQnovUg/iYHUiyqBiRU/NsI2MbE3LnjfrnX2Oec+rZ6gJ7QUqqZdGcF3uRcedxG1fKPQRwgNla3nKHnPPWwi3IUwOElTXFXwUiDG++Zf9+hlxPjo994RJP5dTX5lgFYUfLpDFqD1LEbcAEcjBOTA8EombRRAJlfgpVH/Yx7xv4wYdh1k56hWfgz54AfC3fxodJzkVBBwoGF3ZqIoFO/2t4TyN7gA+WS7D4+M68tq6b3+VFOuuUOkAzzQgC43vvQogUCNGEIx0bj6cfZAwSpBYRnFqPlBYSxEmJJpDhqIPqjvW/XRfLu5AvXcWccJRAWKmlBcQ/kSUSpYMvNbLLJxqFYXr8cbzNW7/3ttDchxXWjKJcd+Tb6hw5+BaNiiZRZVZh5M0C0n+ARyklcxYgSK79vNgDaaMFbmKMTw9Cy2z0GVh+Flb1EVGChTGraJgYr/lKnvYKmTVWgFNQjC95gcUC1MUnZQRj3o=
    - AWS_DEFAULT_REGION=us-east-2
    - AWS_DEFAULT_OUTPUT=table

go:
  - 1.12.x
  - master

os:
  - linux
  - osx

dist: xenial

matrix:
  fast_finish: true
  allow_failures:
    - go: master

before_install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then pip install --user --upgrade awscli; fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then pip install --upgrade awscli; fi
  - if [[ $TRAVIS_OS_NAME == windows ]]; then exit -1; fi
  - aws --version
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b "$(go env GOPATH)/bin" v1.15.0
  - golangci-lint --version
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls

install:
  - go mod vendor

script:
  - golangci-lint run
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - make build
  - ls -lh update-gitignore

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

after_script:
  - aws s3 cp ./update-gitignore "s3://$ARTIFACTS_BUCKET/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_GO_VERSION/update-gitignore-$(go env GOOS)-$(go env GOARCH)"

notifications:
  slack:
    secure: iefNHBLu+kF+JAdxQAt6chIU6VGDMCSSXniARaTp2gq1ERMNeX67WdY4WsqY4R6/EIIPPu0sLR34HnFLgad6IUZiem+zYNmpb4cw+laRE9HC7ItiPr/PRv0oGRa8qx00rogofKPmxYIFKospZ6O3u12s6+b7M8GL59xLk/I92ThiOll/kWnTFEWYcZMYF1IobIjVsvPuoy/P3QPNrtnxUB3+qBMhKSa+0/61AWJbkma8mWnv04VBiHcJGpVYQtH/TCjoQZxsDEm7gx7pF7oW6Fdw+i+sv7+NRdz8lOvLvprUiEePCUlCUh6fIIEne6dRSYT4kKha08t6dba7H5g13egxcaKmqpUlnbyiSIu2I2tPLfEiQgmSLVG1J8bnf0J19kK6QxwZUdFHRN/IypAVjbUVl+CoBOvg9JLOqyCltSiDEEuhT65/VMkulIJDsq6p0E3gkq/f9Xyyy5cPjBJ2viLd1Apgk4KQ9fD64QJryHZl47U+VflRCFaQpvv/B6l6pletFCAMSLqJxycXCjhFlp6FeB2LX8FRdwLau+iwUIeDGxhe0zVWIlIxQV+jBJfl4EKtoEKl6kX6piC02AaRyNg6jwBJWDKjiJvoWB8+gIqWO4ymovzUWExTqCuI13pcbByYbk716OKu2u7kysCx035OR4YcjIwKsdH9SDSWTm4=
